[project]
name = "simity"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "nbformat>=5.10.4",
    "numpy>=2.4.1",
    "scikit-learn>=1.8.0",
    "seaborn>=0.13.2",
]
